# Category assignment for each of the 154 gold invention spans in
# scratchpad_all_invention_286.json, in the same order, from manual reading.
CATEGORIES = [
"OTHER","OTHER","HYBRID","OTHER","TYPE2","OTHER","TYPE1","TYPE2","TYPE1","TYPE1",
"TYPE1","TYPE1","TYPE1","OTHER","HYBRID","HYBRID","HYBRID","HYBRID","OTHER","TYPE2",
"TYPE1","OTHER","TYPE2","TYPE2","TYPE1","TYPE2","TYPE2","HYBRID","OTHER","TYPE2",
"SPECULATIVE","OTHER","TYPE2","TYPE2","OTHER","TYPE2","TYPE2","OTHER","HYBRID","TYPE1",
"TYPE1","HYBRID","OTHER","TYPE2","TYPE2","HYBRID","TYPE2","TYPE2","HYBRID","OTHER",
"TYPE2","OTHER","TYPE2","OTHER","TYPE2","TYPE2","TYPE1","TYPE1","TYPE2","TYPE2",
"TYPE2","TYPE2","HYBRID","TYPE1","TYPE1","HYBRID","TYPE2","TYPE2","TYPE1","HYBRID",
"TYPE1","TYPE1","TYPE1","OTHER","OTHER","TYPE2","TYPE2","TYPE2","TYPE2","TYPE2",
"TYPE2","TYPE2","TYPE2","OTHER","TYPE2","OTHER","TYPE2","TYPE2","TYPE1","TYPE2",
"TYPE1","SPECULATIVE","TYPE1","SPECULATIVE","OTHER","TYPE2","OTHER","TYPE2","OTHER","TYPE2",
"TYPE1","TYPE2","OTHER","TYPE2","TYPE2","OTHER","TYPE2","TYPE2","TYPE2","SPECULATIVE",
"OTHER","SPECULATIVE","TYPE2","TYPE2","OTHER","TYPE2","TYPE1","TYPE2","HYBRID","OTHER",
"HYBRID","OTHER","HYBRID","HYBRID","HYBRID","TYPE2","TYPE2","TYPE2","OTHER","TYPE2",
"TYPE2","TYPE2","TYPE2","OTHER","OTHER","OTHER","TYPE2","TYPE2","OTHER","TYPE2",
"TYPE2","OTHER","TYPE2","TYPE2","TYPE2","TYPE2","SPECULATIVE","TYPE2","OTHER","TYPE2",
"OTHER","TYPE2","TYPE2",
]
